pip_install_packages:
  - name: docker

DATADOG_SITE: datadoghq.com
DATADOG_CHECKS:
  http_check:
    init_config:
    instances:
      - name: Application health check status
        url: "http://localhost:3000"
        timeout: 5
        method: GET
