- hosts: all
  pre_tasks:
    - name: update package cache
      ansible.builtin.apt:
        update_cache: true
  roles:
    - role: geerlingguy.pip
    - role: datadog.datadog
  tasks:
    - name: prepare env
      ansible.builtin.template:
        src: templates/.env.j2
        dest: ~/.env
    - name: deploy
      community.docker.docker_container:
        name: redmine
        image: redmine
        restart_policy: always
        ports:
          - 3000:3000
        env_file: ~/.env
