- hosts: all
  tasks:
    - name: setup tasks
      block:
        - name: update package cache
          ansible.builtin.apt:
            update_cache: true
        - name: import geerlingguy.pip role
          ansible.builtin.import_role:
            name: geerlingguy.pip
          become: yes
        - name: import datadog.datadog role
          ansible.builtin.import_role:
            name: datadog.datadog    
      tags: setup
    - name: deploy tasks
      tags: deploy
      block:
        - name: prepare env
          ansible.builtin.template:
            src: templates/.env.j2
            dest: "{{ env_file_path }}"
        - name: deploy
          community.docker.docker_container:
            name: redmine
            image: redmine
            restart_policy: always
            ports:
              - 3000:3000
            env_file: "{{ env_file_path }}"
